AWSTemplateFormatVersion: 2010-09-09
Description: BinCity AWS Stack

Parameters:

  ProjectName:
    Description: Used as a prefix for project resources. Can be up to 12 characters, lowercase letters (a-z) only.
    Type: String
    Default: bincity
    AllowedPattern: "^[a-z]{1,12}"
    ConstraintDescription: The ProjectName can by up to 12 characters, lowercase letters (a-z) only.
  GitHubOAuthToken:
    Type: String
    NoEcho: true
    MinLength: 40
    MaxLength: 40
    AllowedPattern: '[a-z0-9]*'
  GitHubOwner:
    Type: String
    Default: OscarAC
    AllowedPattern: "[A-Za-z0-9-]+"
  GitHubRepo:
    Type: String
    Default: aws-bincity
    AllowedPattern: "[A-Za-z0-9-]+"
  GitHubBranch:
    Type: String
    Default: develop
    AllowedPattern: "[A-Za-z0-9-]+"

Conditions:
  IADRegion: !Equals [!Ref "AWS::Region", "us-east-1"]

Resources:

  # DynamoDB Table
  TBinCity:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: TBinCity
      AttributeDefinitions:
        - AttributeName: buildingId
          AttributeType: S        
      KeySchema:
        - AttributeName: buildingId
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1

  # Assets S3 Bucket
  AssetsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      MetricsConfigurations:
        - Id: AssetsBucket
      WebsiteConfiguration:
        IndexDocument: index.html

  # Lambda Functions S3 Bucket
  LambdaBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      MetricsConfigurations:
        - Id: LambdaBucket

  # Pipeline Artifacts S3 Bucket
  PipelineArtifactsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled


  # CodeBuild Role
  CodeBuildRole:
    Description: Creating service role in IAM for AWS CodeBuild
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codebuild.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: !Sub '${ProjectName}-codebuild-policy'
          PolicyDocument:
            Statement:
              - Action:
                  - 's3:PutObject'
                  - 's3:GetObject'
                  - 's3:GetObjectVersion'
                  - 's3:GetBucketVersioning'
                Resource:
                  - !Join 
                    - ''
                    - - !GetAtt AssetsBucket.Arn
                      - /*
                  - !Join 
                    - ''
                    - - !GetAtt PipelineArtifactsBucket.Arn
                      - /*
                  - !Join 
                    - ''
                    - - !GetAtt LambdaBucket.Arn
                      - /*         
                Effect: Allow        
        - PolicyName: codebuild-logs
          PolicyDocument:
            Statement:
              - Action:
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                  - 'logs:CreateLogGroup'
                  - 'cloudfront:CreateInvalidation'
                Resource: '*'
                Effect: Allow
      Path: /

  # Assets CodeBuild Project
  AssetsBuildProject:    
    Description: Creating AWS CodeBuild for Web Assets
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub 'Building Assets stage for ${ProjectName}.'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL        
        Image: 'aws/codebuild/standard:2.0'
        Type: LINUX_CONTAINER        
      Name: !Sub '${ProjectName}-build-assets'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE        
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 10
            pre_build:
              commands:                
                - echo Installing NPM dependencies...
                - cd assets
                - npm install fibers node-sass sass redux typescript redux-thunk react-redux --save
                - npm install
            build:
              commands:
                - npm run build
            post_build:
              commands:
                - echo Uploading to AssetsBucket 
                - aws s3 cp --recursive ./build s3://${AssetsBucket}/
                - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/service-worker.js s3://${AssetsBucket}/
                - aws s3 cp --cache-control="max-age=0, no-cache, no-store, must-revalidate" ./build/index.html s3://${AssetsBucket}/                
      TimeoutInMinutes: 5

   # Functions CodeBuild Project
  LambdasBuildProject:    
    Description: Creating AWS CodeBuild for Lambda Functions
    Type: 'AWS::CodeBuild::Project'
    Properties:
      Artifacts:
        Type: CODEPIPELINE
      Description: !Sub 'Building Lambdas stage for ${ProjectName}.'
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL        
        Image: 'aws/codebuild/standard:2.0'
        Type: LINUX_CONTAINER        
      Name: !Sub '${ProjectName}-build-lambdas'
      ServiceRole: !Ref CodeBuildRole
      Source:
        Type: CODEPIPELINE        
        BuildSpec: !Sub |
          version: 0.2
          phases:
            install:
              runtime-versions:
                nodejs: 10
            build:
              commands:                                
                - cd functions
                - aws cloudformation package --template-file ./functions-stack.yml --output-template-file outputtemplate.yml --s3-bucket ${LambdaBucket}
                - aws cloudformation deploy --template-file ./outputtemplate.yml --stack-name ${ProjectName}-Lambdas --capabilities CAPABILITY_IAM            
      TimeoutInMinutes: 5

  # CloudFormation Role  
  CloudFormationRole: 
    Properties: 
      AssumeRolePolicyDocument: 
        Statement: 
          Action: 
            - "sts:AssumeRole"
          Effect: Allow
          Principal: 
            Service: 
              - cloudformation.amazonaws.com
        Version: "2012-10-17"
      ManagedPolicyArns: 
        - "arn:aws:iam::aws:policy/AdministratorAccess"
      Path: /
    Type: "AWS::IAM::Role"

  # CodePipeline Role
  CodePipelineRole:
    Description: Creating service role in IAM for AWS CodePipeline
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - codepipeline.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: passrole-for-pipeline
          PolicyDocument: 
            Statement: 
              - Action: 
                  - "iam:PassRole"                
                Effect: Allow
                Resource: !GetAtt 
                  - CloudFormationRole
                  - Arn
        - PolicyName: artifacts-for-pipeline
          PolicyDocument:
            Statement:
              - Action:
                  - 's3:PutObject'
                  - 's3:GetObject'                  
                Resource:
                  'Fn::Join':
                    - ''
                    - - 'Fn::GetAtt':
                          - PipelineArtifactsBucket
                          - Arn
                      - /*
                Effect: Allow
              - Action:            
                  - cloudformation:*
                Resource: "*"
                Effect: Allow
        - PolicyName: codebuild-assets-for-pipeline
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: !GetAtt 
                  - AssetsBuildProject
                  - Arn
                Effect: Allow      
        - PolicyName: codebuild-lambdas-for-pipeline
          PolicyDocument:
            Statement:
              - Action:
                  - 'codebuild:BatchGetBuilds'
                  - 'codebuild:StartBuild'
                Resource: !GetAtt 
                  - LambdasBuildProject
                  - Arn
                Effect: Allow

  # Project Pipeline
  ProjectCodePipeline:
    Type: 'AWS::CodePipeline::Pipeline'
    Properties:
      Name: !Sub '${ProjectName}-Pipeline'
      RoleArn: !GetAtt 
        - CodePipelineRole
        - Arn
      ArtifactStore:
        Location: !Ref PipelineArtifactsBucket
        Type: S3
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              InputArtifacts: []
              ActionTypeId:
                Version: '1'
                Category: Source
                Owner: ThirdParty
                Provider: GitHub
              Configuration:
                Owner: !Ref GitHubOwner
                Repo: !Ref GitHubRepo
                Branch: !Ref GitHubBranch
                PollForSourceChanges: true
                OAuthToken: !Ref GitHubOAuthToken
              OutputArtifacts:
                - Name: !Sub '${ProjectName}-SourceArtifact'
        - Name: Build-Lambdas
          Actions:
            - Name: build-and-deploy-lambdas
              InputArtifacts:
                - Name: !Sub '${ProjectName}-SourceArtifact'
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: !Sub '${ProjectName}-Assets-BuildArtifact'
              Configuration:
                ProjectName: !Sub '${ProjectName}-build-lambdas'
              RunOrder: 1        
        - Name: Build-Assets
          Actions:
            - Name: build-and-deploy-assets
              InputArtifacts:
                - Name: !Sub '${ProjectName}-SourceArtifact'
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: '1'
                Provider: CodeBuild
              OutputArtifacts:
                - Name: !Sub '${ProjectName}-Assets-BuildArtifact'
              Configuration:
                ProjectName: !Sub '${ProjectName}-build-assets'
              RunOrder: 1             
    DependsOn:
      -  PipelineArtifactsBucket