export const FETCH_BUILDINGS = 'FETCH_BUILDINGS';
export const FETCH_CURRENT_BUILDING = 'FETCH_CURRENT_BUILDING';
export const SET_CURRENT_BUILDING = 'SET_CURRENT_BUILDING';
export const UPDATE_CURRENT_BUILDING = 'UPDATE_BUILDING';

export const FETCH_AUTH = 'FETCH_AUTH';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';

export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';


// export const FETCH_BUILDINGS_FLOORS = 'FETCH_BUILDINGS_FLOORS';
// export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS';
// export const CREATE_BUILDING = 'NEW_BUILDING';