export const FETCH_BUILDINGS = 'FETCH_BUILDINGS';
export const FETCH_CURRENT_BUILDING = 'FETCH_CURRENT_BUILDING';
export const SET_CURRENT_BUILDING = 'SET_CURRENT_BUILDING';
export const UPDATE_CURRENT_BUILDING = 'UPDATE_BUILDING';

export const FETCH_AUTH = 'FETCH_AUTH';
export const LOGOUT = 'LOGOUT';


// export const FETCH_BUILDINGS_FLOORS = 'FETCH_BUILDINGS_FLOORS';
// export const UPDATE_BUILDINGS = 'UPDATE_BUILDINGS';
// export const CREATE_BUILDING = 'NEW_BUILDING';