export const FETCH_APARTMENTS_STARTED = 'FETCH_APARTMENTS_STARTED';
export const FETCH_APARTMENTS_SUCCESS = 'FETCH_APARTMENTS_SUCCESS';
export const FETCH_APARTMENTS_ERROR = 'FETCH_APARTMENTS_ERROR';
export const SET_CURRENT_BUILDING = 'SET_CURRENT_BUILDING';
export const UPDATE_APARTMENTS_STATE = 'UPDATE_APARTMENTS_STATE';

export const APARTMENTS_NEWFLOOR_STARTED = 'APARTMENTS_NEWFLOOR_STARTED';
export const APARTMENTS_NEWFLOOR_SUCCESS = 'APARTMENTS_NEWFLOOR_SUCCESS';
export const APARTMENTS_NEWFLOOR_ERROR = 'APARTMENTS_NEWFLOOR_ERROR';

export const APARTMENTS_DELETE_STARTED = 'APARTMENTS_DELETE_STARTED';
export const APARTMENTS_DELETE_SUCCESS = 'APARTMENTS_DELETE_SUCCESS';
export const APARTMENTS_DELETE_ERROR = 'APARTMENTS_DELETE_ERROR';

export const APARTMENTS_SAVE_REALTIME = 'APARTMENTS_SAVE_REALTIME';
export const APARTMENTS_SAVE_STARTED = 'APARTMENTS_SAVE_STARTED';
export const APARTMENTS_SAVE_SUCCESS = 'APARTMENTS_SAVE_SUCCESS';
export const APARTMENTS_SAVE_ERROR = 'APARTMENTS_SAVE_ERROR';

export const FETCH_AUTH = 'FETCH_AUTH';
export const LOGIN_STARTED = 'LOGIN_STARTED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const NEW_PASSWORD_REQUIRED = 'NEW_PASSWORD_REQUIRED';

export const LOGOUT = 'LOGOUT';

export const SIGNUP_STARTED = 'SIGNUP_STARTED';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR = 'SIGNUP_ERROR';

export const SIGNUP_CONFIRM_STARTED = 'SIGNUP_CONFIRM_STARTED';
export const SIGNUP_CONFIRM_SUCCESS = 'SIGNUP_CONFIRM_SUCCESS';
export const SIGNUP_CONFIRM_ERROR = 'SIGNUP_CONFIRM_ERROR';